### PR TITLE
Fix for issue #456

### PR DESCRIPTION
**Pull request by mbudiu-vmw**

### CODE REVIEW

**Comment by mbudiu-vmw** [comment]
@SivaMaplelabs : does this address issue #456?

**Comment by SivaMaplelabs** [comment]
@mbudiu-vmw I don't think this PR address the issue, https://github.com/vmware/hillview/issues/456
It's not behaving as same as https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_input_required
Still, it is proceeding if the user does not provide values for the mandatory fields.

**Comment by SivaMaplelabs** [comment]
If the field is empty it is showing as "Please fill out this field" but still proceeding.

**Comment by mbudiu-vmw** [comment]
I have amended the pull request, I think that now validation is done properly.

**Comment by SivaMaplelabs** [comment]
@mbudiu-vmw Looks pretty good now.

**Comment by SivaMaplelabs** [comment]
@mbudiu-vmw  So the user and password are optional to load DB table?

**Comment by mbudiu-vmw** [comment]
Yes, the user and password are optional.

**Pull request merged**
